### ISSUE TITLE
Hangs the browser

### ISSUE THREAD

**Issue by shyamchandranmec** [Affectiva/developerportal#127]
Hi I was running affdex.js to detect emotions. After running it continuously for around 30 mins the browser was not responding. The whole system went slow. Finally I had to Force Quit chrome to bring the system back to normal. 
Any solution to this?

**Comment by umangmehta12** [comment]
@shyamchandranmec Can you provide details about your system, browser information, the sample application that you are running (https://github.com/Affectiva/js-sdk-sample-apps). I would recommend given a brief issue report with the stack trace in the console log either to [gitter](https://gitter.im/Affectiva/sdk) or StackOverflow with affdex-sdk (https://stackoverflow.com/tags/affdex-sdk) or an issue with the sample apps (https://github.com/Affectiva/js-sdk-sample-apps/issues). I am planning to close this issue since this is not related to the developer-portal.

**Comment by umangmehta12** [comment]
@shyamchandranmec I am closing this issue, you can log another issue in the sample app repository with more information.
